

pipeline {
  agent any
  environment {
    version = sh (
      script: 'git log --no-merges -1 --pretty=%h',
      returnStdout: true
    ).trim()
  }


  stages {
    stage("Build step1") {
      steps {
        sh "echo ${version}"

      }
    }

    stage("build step2") {
      steps {
        sh "sleep 30"
      }
    }



    stage("Deploy step1") {

      steps {
        sh "echo prod deployment"
      }
    }

  }
  post {
      always {
       sh "echo completed!"
      }

   }
}

