

pipeline {
  agent any
  environment {
    version = sh (
      script: 'git log --no-merges -1 --pretty=%h',
      returnStdout: true
    ).trim()
  }
  options{
    disableConcurrentBuilds()
  }

  stages {
    stage("Build step1") {
      steps {
        dir('files') {
          git branch 'develop'
              url: 'https://github.com/khoshalarpy/devopsTest.git'
        }
        sh "build step1"

      }
    }

    stage("build step2") {
      steps {
        sh "sleep 30"
      }
    }



    stage("Deploy step1") {

      steps {
        sh "echo prod deployment"
      }
    }

  }
  post {
      always {

          // Publish code coverage report
      }

   }
}

